#!/usr/bin/env python3
"""
Generate docs/field-reference.md from the field registry.

Usage:
    python scripts/gen_field_reference.py            # write the file
    python scripts/gen_field_reference.py --check    # exit 1 if the file is out of date
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tv_mcp.field_registry import FIELD_CATEGORIES, FIELD_METADATA, get_all_fields  # noqa: E402

OUTPUT = ROOT / "docs" / "field-reference.md"

CATEGORY_TITLES = {
    "trend": "Trend",
    "momentum": "Momentum",
    "volatility": "Volatility",
    "volume_flow": "Volume & Flow",
    "composite_signals": "Composite Signals (TradingView ratings)",
    "price_structure": "Price & Structure",
    "valuation": "Valuation",
    "profitability": "Profitability",
    "growth": "Growth",
    "balance_sheet": "Balance Sheet",
    "quality_scores": "Quality Scores",
    "performance": "Performance",
    "price_extremes": "Price Extremes",
    "gap": "Gaps",
    "dividend": "Dividends",
    "etf_fund": "ETF / Fund",
    "ipo": "IPO",
    "advanced_technical": "Advanced Technical",
    "candlestick_patterns": "Candlestick Patterns",
}


def _range(r) -> str:
    if not r:
        return "—"
    lo, hi = r
    lo = "−∞" if lo is None else lo
    hi = "∞" if hi is None else hi
    return f"{lo} … {hi}"


def render() -> str:
    fields = get_all_fields()
    lines = [
        "# Field reference",
        "",
        f"tv-mcp exposes **{len(fields)} TradingView screener fields** in **{len(FIELD_CATEGORIES)} categories**. "
        "Use these exact names in `columns`, `filters[].left`, `filters[].right` (field-to-field comparison) and `sort_by`.",
        "",
        "Field names follow the TradingView scanner API; see the community list at "
        "<https://shner-elmo.github.io/TradingView-Screener/fields/stocks.html> for fields not yet included here. "
        "Availability of a value can vary by market and instrument type (for example ETF and IPO fields are null for most stocks).",
        "",
        "_This file is generated by `scripts/gen_field_reference.py` from `src/tv_mcp/field_registry.py`. Do not edit by hand._",
        "",
        "## Categories",
        "",
        "| Category | Fields |",
        "|----------|--------|",
    ]
    for key in FIELD_CATEGORIES:
        lines.append(f"| [{CATEGORY_TITLES.get(key, key)}](#{CATEGORY_TITLES.get(key, key).lower().replace(' ', '-').replace('/', '').replace('(', '').replace(')', '').replace('&', '').replace('--', '-')}) | {len(FIELD_CATEGORIES[key])} |")
    lines.append("")
    for key, names in FIELD_CATEGORIES.items():
        lines += [f"## {CATEGORY_TITLES.get(key, key)}", "", "| Field | Type | Units | Range | Description |", "|-------|------|-------|-------|-------------|"]
        for name in sorted(names, key=str.lower):
            m = FIELD_METADATA[name]
            lines.append(f"| `{name}` | {m['type']} | {m['units']} | {_range(m['range'])} | {m['description']} |")
        lines.append("")
    lines += [
        "## Filter operations",
        "",
        "`greater`, `egreater`, `less`, `eless`, `equal`, `nequal`, `in_range`, `not_in_range`, `above%`, `below%`, "
        "`in_range%`, `not_in_range%`, `crosses`, `crosses_above`, `crosses_below`, `has`, `has_none_of`, `match`, "
        "`nmatch`, `empty`, `nempty`, `in_day_range`, `in_week_range`, `in_month_range`.",
        "",
        "`right` may be a number, a string, a list (for `in_range`/`has`), or another field name (for example "
        '`{"left": "close", "op": "greater", "right": "EMA200"}`).',
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT} is out of date; run: python scripts/gen_field_reference.py", file=sys.stderr)
            return 1
        print("docs/field-reference.md is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT} ({len(get_all_fields())} fields)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
